//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleventhDay.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departments()
        {
            this.Halls = new HashSet<Halls>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Boss { get; set; }
        public string Phone { get; set; }
        public string OfficeDean { get; set; }
        public int ChiefID { get; set; }
        public int UnitID { get; set; }
        public System.DateTime DateStart { get; set; }
        public decimal Cost { get; set; }
        public short CostYear { get; set; }
        public decimal CostAfter { get; set; }
        public short Period { get; set; }
    
        public virtual Chiefs Chiefs { get; set; }
        public virtual Units Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Halls> Halls { get; set; }
    }
}
